apiVersion: v1
kind: Service
metadata:
  name: inference-server
  namespace: model-sim
spec:
  selector:
    app: inference-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  sessionAffinity: None

